application:
  port: 8000
  host: "127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@email.com"
  # During prod, we inject the token via environment
  # variables that take place over the hard-coded config
  auth_token: "mock-token-for-development"
